### ISSUE TITLE
[CI] Change dependabot's configuration so that publish doesn't fail 

### ISSUE THREAD

**Issue by radovix** [Enterwell/react-form-validation#41]
Each time after dependabot's PR is merged, build and publish are triggered and publish fails because package's version isn't bumped. 

We should see what's the best solution for this problem.

**Comment by AleksandarDev** [comment]
[Changelog Manager] (https://github.com/Enterwell/ChangelogManager) looks interesting 😁

**Comment by AleksandarDev** [comment]
https://github.com/Enterwell/react-form-validation/issues/60 this would solve reported issue
